### ISSUE TITLE
ReadMe example misleading re. `--`

### ISSUE THREAD

**Issue by AndrewDDavis** [UmkaDK/getopts_long#19]
The example in the ReadMe has this snippet near the end:

```sh
shift $(( OPTIND - 1 ))
[[ "${1}" == "--" ]] && shift
```

However, when `getopts` encounters `--` in the arguments list, it returns with status 1 _and increments `OPTIND`_. So the `--` would have been shifted away in the line above, and the only way the test would succeed is if `--` was given twice consecutively in the arguments.

**Comment by UrsaDK** [comment]
You're absolutely right! 🙂 I'll update the README and remove that line from test scripts. 👍 Thank you!!
